name: scalable_image
description: A widget that shows an image which can be scaled and dragged using gestures
version: 1.1.2
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/scalable_image

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

